include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - firebase/**
    - lib/presentation/screens/mistake_notebook_screen.dart
  errors:
    deprecated_member_use: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    unnecessary_import: ignore
    uri_does_not_exist: ignore
    unused_element: ignore
    unused_field: ignore
    unused_local_variable: ignore
    unnecessary_null_comparison: ignore
    unnecessary_cast: ignore
