targets:
  $default:
    builders:
      isar_generator:
        generate_for:
          - lib/data/local/isar/schemas/achievement_schema.dart
          - lib/data/local/isar/schemas/chapter_schema.dart
          - lib/data/local/isar/schemas/mistake_entry_schema.dart
          - lib/data/local/isar/schemas/mock_test_schema.dart
          - lib/data/local/isar/schemas/plan_entry_schema.dart
          - lib/data/local/isar/schemas/revision_schedule_schema.dart
          - lib/data/local/isar/schemas/study_log_schema.dart
          - lib/data/local/isar/schemas/user_schema.dart
          - lib/data/local/isar/schemas/user_settings_schema.dart
